{{- if .Values.celery.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pydici.fullname" . }}-celery-worker
  labels:
    {{- include "pydici.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  replicas: {{ .Values.celery.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "pydici.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      labels:
        {{- include "pydici.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
        app.kubernetes.io/name: {{ include "pydici.fullname" . }}-celery-worker
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: wait-for-redis
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for Redis to be ready..."
          until nc -z {{ include "pydici.redisHost" . }} {{ .Values.redis.service.port }}; do
            echo "Redis not ready, sleeping..."
            sleep 2
          done
          echo "Redis is ready!"
      containers:
      - name: celery-worker
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.pydici.image.registry }}/{{ .Values.pydici.image.repository }}:{{ .Values.pydici.image.tag }}"
        imagePullPolicy: {{ .Values.pydici.image.pullPolicy }}
        command:
        - celery
        - -A
        - pydici
        - worker
        - --loglevel=info
        - --concurrency=2
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "pydici.fullname" . }}-django
              key: secret-key
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pydici.fullname" . }}-mariadb
              key: mariadb-password
        envFrom:
        - configMapRef:
            name: {{ include "pydici.fullname" . }}-django
        resources:
          {{- toYaml .Values.celery.worker.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}