apiVersion: v1
kind: Service
metadata:
  name: {{ include "pydici.fullname" . }}
  labels:
    {{- include "pydici.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
spec:
  type: {{ .Values.pydici.service.type }}
  ports:
  - port: {{ .Values.pydici.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "pydici.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: django