{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pydici.fullname" . -}}
{{- $svcPort := .Values.pydici.service.port -}}
{{- if and .Values.ingress.className (not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
{{- end }}
{{- if .Values.ingress.certManager.enabled }}
  {{- $_ := set .Values.ingress.annotations "cert-manager.io/cluster-issuer" .Values.ingress.certManager.issuer }}
  {{- if eq .Values.ingress.certManager.issuerKind "Issuer" }}
    {{- $_ := set .Values.ingress.annotations "cert-manager.io/issuer" .Values.ingress.certManager.issuer }}
    {{- $_ := unset .Values.ingress.annotations "cert-manager.io/cluster-issuer" }}
  {{- end }}
{{- end }}
{{- if and .Values.ingress.basicAuth.enabled }}
  {{- $_ := set .Values.ingress.annotations "nginx.ingress.kubernetes.io/auth-type" "basic" }}
  {{- $_ := set .Values.ingress.annotations "nginx.ingress.kubernetes.io/auth-secret" (printf "%s-basic-auth" $fullName) }}
  {{- $_ := set .Values.ingress.annotations "nginx.ingress.kubernetes.io/auth-realm" "pydici" }}
  {{- $_ := set .Values.ingress.annotations "nginx.ingress.kubernetes.io/auth-response-headers" "Remote-User" }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "pydici.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if or .Values.ingress.tls .Values.ingress.certManager.enabled }}
  tls:
    {{- if .Values.ingress.certManager.enabled }}
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ .host | quote }}
      secretName: {{ $fullName }}-tls-{{ .host | replace "." "-" }}
    {{- end }}
    {{- else }}
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}