{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pydici.fullname" . }}-mariadb
  labels:
    {{- include "pydici.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
  - port: {{ .Values.mariadb.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    {{- include "pydici.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
{{- end }}