{{- if .Values.memcached.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pydici.fullname" . }}-memcached
  labels:
    {{- include "pydici.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  type: {{ .Values.memcached.service.type }}
  ports:
  - port: {{ .Values.memcached.service.port }}
    targetPort: memcached
    protocol: TCP
    name: memcached
  selector:
    {{- include "pydici.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
{{- end }}