{{- if and .Values.networkPolicies.enabled .Values.celery.worker.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pydici.fullname" . }}-celery-worker
  labels:
    {{- include "pydici.labels" . | nindent 4 }}
    app.kubernetes.io/component: networkpolicy
spec:
  podSelector:
    matchLabels:
      {{- include "pydici.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress:
  - to: []
    ports:
    - protocol: UDP
      port: 53
  {{- if .Values.mariadb.enabled }}
  - to:
    - podSelector:
        matchLabels:
          {{- include "pydici.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: mariadb
    ports:
    - protocol: TCP
      port: 3306
  {{- end }}
  {{- if .Values.redis.enabled }}
  - to:
    - podSelector:
        matchLabels:
          {{- include "pydici.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: redis
    ports:
    - protocol: TCP
      port: 6379
  {{- end }}
  {{- if .Values.memcached.enabled }}
  - to:
    - podSelector:
        matchLabels:
          {{- include "pydici.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: memcached
    ports:
    - protocol: TCP
      port: 11211
  {{- end }}
  {{- if eq .Values.networkPolicies.mode "permissive" }}
  - to: []
  {{- end }}
{{- end }}